In [1]:
import pandas as pd

In [2]:
product=pd.read_csv("products.csv")

suppliers=pd.read_csv("suppliers.csv")

In [3]:
purchase_orders=pd.read_csv("purchase_orders.csv")

In [4]:
sales=pd.read_csv("sales.csv")

In [5]:
inventory_snapshot=pd.read_csv("inventory_snapshot.csv")

In [6]:
daily_inventory=pd.read_csv("daily_inventory.csv")

In [7]:
#preview first 5 rows of all tables

In [8]:
product.head()

,sku_id,product_name,category,sub_category,brand,product_type,size_label,launch_date,shelf_life_months,parent_sku,default_price,primary_supplier_id,is_active,country_of_origin,online_only,avg_rating,rating_count,is_discontinued
0,SKU9310518635,Garnier Sunscreen 50ml,Beauty,Skincare & Cosmetics,Garnier,Sunscreen,50ml,2019-04-22,18.0,SKU5304202933,17.74,200139,True,UK,False,3.93,73,False
1,SKU6955836996,Adidas Running Shoes Standard,Sports & Lifestyle,Sports Gear,Adidas,Running Shoes,Standard,2016-08-13,NaN,NaN,44.64,200856,True,CN,False,3.26,485,False
2,SKU6171745695,Puma Gym Towel Standard,Sports & Lifestyle,Sports Gear,Puma,Gym Towel,Standard,2017-01-26,NaN,NaN,63.71,200983,True,JP,False,3.44,329,False
3,SKU9112068923,Samsung Power Bank 10000mAh,Electronics Accessories,Gadgets,Samsung,Power Bank,10000mAh,2019-04-21,NaN,NaN,49.10,200439,True,AU,False,4.33,183,False
4,SKU4171552432,Sony USB Charger 33W,Electronics Accessories,Gadgets,Sony,USB Charger,33W,2016-04-24,NaN,SKU1416947255,41.20,200991,True,US,False,4.48,56,False

In [9]:
purchase_orders.head()

,Unnamed: 0,po_id,sku_id,supplier_id,po_date,promised_delivery_date,delivery_date,order_qty,unit_cost,shipping_mode,status,incoterm,currency,freight_cost,duty_cost
0,0,PO03732421,SKU9310518635,200139,2019-05-22,2019-06-12,2019-06-18,106,13.65,Air,delivered,EXW,EUR,7.01,10.44
1,1,PO72647743,SKU9310518635,200139,2019-06-03,2019-06-24,2019-06-27,159,11.37,Air,delivered,EXW,EUR,25.97,17.82
2,2,PO41745551,SKU9310518635,200139,2019-09-03,2019-09-24,2019-09-19,154,12.03,Air,delivered,EXW,EUR,8.51,16.78
3,3,PO95292145,SKU9310518635,200139,2019-12-04,2019-12-25,2019-12-21,94,14.15,Air,delivered,EXW,EUR,18.91,6.70
4,4,PO94595741,SKU9310518635,200139,2020-03-04,2020-03-25,2020-03-25,90,11.42,Air,delivered,EXW,EUR,20.69,6.11

In [10]:
inventory_snapshot.head()

,snapshot_date,sku_id,current_stock,incoming_stock,stock_age_days,warehouse_stock,retail_stock,amazon_allocated,tiktokshop_allocated,zalora_allocated,reorder_point,safety_stock,backorder_qty,opening_buffer
0,2022-12-31,SKU9310518635,360,0,674,280,80,59,41,30,28,6,0,29
1,2022-12-31,SKU6955836996,768,0,1165,497,271,167,59,67,34,4,0,29
2,2022-12-31,SKU6171745695,915,0,1082,570,345,187,77,88,41,6,5,35
3,2022-12-31,SKU9112068923,525,0,675,338,187,70,34,65,67,14,0,2
4,2022-12-31,SKU4171552432,1098,0,1221,556,542,90,76,106,22,3,0,24

In [11]:
sales.head()

,sale_id,order_id,date,sku_id,channel,quantity,unit_price,promo_flag,discount_pct,event_name,customer_segment_id,customer_segment,device_type,payment_method,shipping_fee,voucher_amount,net_revenue,returned_flag,quarter_bucket,month
0,97746642,ORD97746642,2019-04-22,SKU9310518635,Amazon,1,17.74,0,0.0,NaN,2,premium,mobile_app,e_wallet,0.23,0.0,17.97,0,2019Q2,2019-04-01
1,98635846,ORD98635846,2019-04-25,SKU9310518635,Amazon,1,17.74,0,0.0,NaN,1,value,mobile_app,debit_card,1.62,0.0,19.36,0,2019Q2,2019-04-01
2,12607411,ORD12607411,2019-04-27,SKU9310518635,Zalora,1,17.74,0,0.0,NaN,1,value,mobile_app,debit_card,3.84,0.0,21.58,0,2019Q2,2019-04-01
3,90411177,ORD90411177,2019-04-28,SKU9310518635,TikTokShop,1,17.74,0,0.0,NaN,2,premium,mobile_web,e_wallet,2.61,0.0,20.35,0,2019Q2,2019-04-01
4,40822201,ORD40822201,2019-04-28,SKU9310518635,Zalora,2,17.74,0,0.0,NaN,1,value,mobile_app,credit_card,1.26,0.0,36.74,0,2019Q2,2019-04-01

In [12]:
daily_inventory.head()

,snapshot_date,sku_id,current_stock,daily_sales,incoming_stock,warehouse_stock,retail_stock,amazon_allocated,tiktokshop_allocated,zalora_allocated,reorder_point,safety_stock
0,2016-01-01,SKU9310518635,29,0,1606,17,12,5,3,1,15,0
1,2016-01-01,SKU6955836996,29,0,2328,17,12,5,3,1,6,0
2,2016-01-01,SKU6171745695,35,0,2761,21,14,6,4,2,5,0
3,2016-01-01,SKU9112068923,2,0,3371,1,1,0,0,0,10,0
4,2016-01-01,SKU4171552432,24,0,2178,14,10,4,2,1,18,0

In [13]:
suppliers=pd.read_csv("suppliers.csv")

In [14]:
suppliers.head(10)

,supplier_id,supplier_name,region,default_shipping_mode,status,lead_time_category,min_order_qty,contract_start_date
0,200856,Unilever Global Markets,UK,Sea,active,long,400,2011-01-24
1,200345,Procter & Gamble EMEA,DE,Sea,active,long,400,2014-04-08
2,200983,Nestle Consumer Products,MY,Land,active,short,100,2012-12-04
3,200099,Samsung Electronics,KR,Sea,active,long,400,2018-02-19
4,200271,LG Electronics,KR,Sea,active,long,400,2016-01-01
5,200160,Philips Domestic Appliances,NL,Sea,active,long,400,2011-04-08
6,200924,Sony Lifestyle Products,JP,Sea,active,medium,200,2018-10-01
7,200485,IKEA Home Furnishings,SE,Sea,active,long,400,2018-04-23
8,200139,L'Oreal Beauty Distribution,FR,Air,active,long,400,2018-07-08
9,200889,Johnson & Johnson Consumer,US,Air,active,long,400,2017-10-09

In [15]:
#data information

In [16]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sku_id               80 non-null     str
 1   product_name         80 non-null     str
 2   category             80 non-null     str
 3   sub_category         80 non-null     str
 4   brand                80 non-null     str
 5   product_type         80 non-null     str
 6   size_label           80 non-null     str
 7   launch_date          80 non-null     str
 8   shelf_life_months    26 non-null     float64
 9   parent_sku           10 non-null     str
 10  default_price        80 non-null     float64
 11  primary_supplier_id  80 non-null     int64
 12  is_active            80 non-null     bool
 13  country_of_origin    80 non-null     str
 14  online_only          80 non-null     bool
 15  avg_rating           80 non-null     float64
 16  rating_count         80 non-null     int64
 17  is_discontinued      80 non-null     bool
dtypes: bool(3), float64(3), int64(2), str(10)
memory usage: 9.7 KB

In [17]:
purchase_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1144 non-null   int64
 1   po_id                   1144 non-null   str
 2   sku_id                  1144 non-null   str
 3   supplier_id             1144 non-null   int64
 4   po_date                 1144 non-null   str
 5   promised_delivery_date  1144 non-null   str
 6   delivery_date           1144 non-null   str
 7   order_qty               1144 non-null   int64
 8   unit_cost               1144 non-null   float64
 9   shipping_mode           1144 non-null   str
 10  status                  1144 non-null   str
 11  incoterm                1144 non-null   str
 12  currency                1144 non-null   str
 13  freight_cost            1144 non-null   float64
 14  duty_cost               1144 non-null   float64
dtypes: float64(3), int64(3), str(9)
memory usage: 134.2 KB

In [18]:
inventory_snapshot.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   snapshot_date         80 non-null     str
 1   sku_id                80 non-null     str
 2   current_stock         80 non-null     int64
 3   incoming_stock        80 non-null     int64
 4   stock_age_days        80 non-null     int64
 5   warehouse_stock       80 non-null     int64
 6   retail_stock          80 non-null     int64
 7   amazon_allocated      80 non-null     int64
 8   tiktokshop_allocated  80 non-null     int64
 9   zalora_allocated      80 non-null     int64
 10  reorder_point         80 non-null     int64
 11  safety_stock          80 non-null     int64
 12  backorder_qty         80 non-null     int64
 13  opening_buffer        80 non-null     int64
dtypes: int64(12), str(2)
memory usage: 8.9 KB

In [19]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 160131 entries, 0 to 160130
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   sale_id              160131 non-null  int64
 1   order_id             160131 non-null  str
 2   date                 160131 non-null  str
 3   sku_id               160131 non-null  str
 4   channel              160131 non-null  str
 5   quantity             160131 non-null  int64
 6   unit_price           160131 non-null  float64
 7   promo_flag           160131 non-null  int64
 8   discount_pct         160131 non-null  float64
 9   event_name           9704 non-null    str
 10  customer_segment_id  160131 non-null  int64
 11  customer_segment     160131 non-null  str
 12  device_type          160131 non-null  str
 13  payment_method       160131 non-null  str
 14  shipping_fee         160131 non-null  float64
 15  voucher_amount       160131 non-null  float64
 16  net_revenue          160131 non-null  float64
 17  returned_flag        160131 non-null  int64
 18  quarter_bucket       160131 non-null  str
 19  month                160131 non-null  str
dtypes: float64(5), int64(5), str(10)
memory usage: 24.4 MB

In [20]:
daily_inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 204560 entries, 0 to 204559
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   snapshot_date         204560 non-null  str
 1   sku_id                204560 non-null  str
 2   current_stock         204560 non-null  int64
 3   daily_sales           204560 non-null  int64
 4   incoming_stock        204560 non-null  int64
 5   warehouse_stock       204560 non-null  int64
 6   retail_stock          204560 non-null  int64
 7   amazon_allocated      204560 non-null  int64
 8   tiktokshop_allocated  204560 non-null  int64
 9   zalora_allocated      204560 non-null  int64
 10  reorder_point         204560 non-null  int64
 11  safety_stock          204560 non-null  int64
dtypes: int64(10), str(2)
memory usage: 18.7 MB

In [21]:
suppliers.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   supplier_id            25 non-null     int64
 1   supplier_name          25 non-null     str
 2   region                 25 non-null     str
 3   default_shipping_mode  25 non-null     str
 4   status                 25 non-null     str
 5   lead_time_category     25 non-null     str
 6   min_order_qty          25 non-null     int64
 7   contract_start_date    25 non-null     str
dtypes: int64(2), str(6)
memory usage: 1.7 KB

In [22]:
#check missing values

In [23]:
product.isnull().sum()

sku_id                  0
product_name            0
category                0
sub_category            0
brand                   0
product_type            0
size_label              0
launch_date             0
shelf_life_months      54
parent_sku             70
default_price           0
primary_supplier_id     0
is_active               0
country_of_origin       0
online_only             0
avg_rating              0
rating_count            0
is_discontinued         0
dtype: int64

In [24]:
purchase_orders.isnull().sum()

Unnamed: 0                0
po_id                     0
sku_id                    0
supplier_id               0
po_date                   0
promised_delivery_date    0
delivery_date             0
order_qty                 0
unit_cost                 0
shipping_mode             0
status                    0
incoterm                  0
currency                  0
freight_cost              0
duty_cost                 0
dtype: int64

In [25]:
inventory_snapshot.isnull().sum()

snapshot_date           0
sku_id                  0
current_stock           0
incoming_stock          0
stock_age_days          0
warehouse_stock         0
retail_stock            0
amazon_allocated        0
tiktokshop_allocated    0
zalora_allocated        0
reorder_point           0
safety_stock            0
backorder_qty           0
opening_buffer          0
dtype: int64

In [26]:
sales.isnull().sum()

sale_id                     0
order_id                    0
date                        0
sku_id                      0
channel                     0
quantity                    0
unit_price                  0
promo_flag                  0
discount_pct                0
event_name             150427
customer_segment_id         0
customer_segment            0
device_type                 0
payment_method              0
shipping_fee                0
voucher_amount              0
net_revenue                 0
returned_flag               0
quarter_bucket              0
month                       0
dtype: int64

In [27]:
daily_inventory.isnull().sum()

snapshot_date           0
sku_id                  0
current_stock           0
daily_sales             0
incoming_stock          0
warehouse_stock         0
retail_stock            0
amazon_allocated        0
tiktokshop_allocated    0
zalora_allocated        0
reorder_point           0
safety_stock            0
dtype: int64

In [28]:
suppliers.isnull().sum()

supplier_id              0
supplier_name            0
region                   0
default_shipping_mode    0
status                   0
lead_time_category       0
min_order_qty            0
contract_start_date      0
dtype: int64

In [29]:
#handling missing values

In [30]:
product['shelf_life_months']=product['shelf_life_months'].fillna(product['shelf_life_months'].median())

In [31]:
product['parent_sku']=product['parent_sku'].fillna('No parent sku')

In [32]:
sales['event_name']=sales['event_name'].fillna('No event')

In [33]:
#check duplicate rows

In [34]:
product.duplicated().sum()

np.int64(0)

In [35]:
purchase_orders.duplicated().sum()

np.int64(0)

In [36]:
inventory_snapshot.duplicated().sum()

np.int64(0)

In [37]:
sales.duplicated().sum()

np.int64(0)

In [38]:
daily_inventory.duplicated().sum()

np.int64(0)

In [39]:
suppliers.duplicated().sum()

np.int64(0)

In [40]:
#remove extra spaces from column names

product.columns=product.columns.str.strip()

In [41]:
purchase_orders.columns=purchase_orders.columns.str.strip()

In [42]:
inventory_snapshot.columns=inventory_snapshot.columns.str.strip()

In [43]:
sales.columns=sales.columns.str.strip()

In [44]:
daily_inventory.columns=daily_inventory.columns.str.strip()

In [45]:
suppliers.columns=suppliers.columns.str.strip()

In [46]:
#data type change

In [47]:
product['launch_date']=pd.to_datetime(product['launch_date'])

In [48]:
purchase_orders['po_date']=pd.to_datetime(purchase_orders['po_date'])

In [49]:
purchase_orders['promised_delivery_date']=pd.to_datetime(purchase_orders['promised_delivery_date'])

In [50]:
purchase_orders['delivery_date']=pd.to_datetime(purchase_orders['delivery_date'])

In [51]:
inventory_snapshot['snapshot_date']=pd.to_datetime(inventory_snapshot['snapshot_date'])

In [52]:
sales['date']=pd.to_datetime(sales['date'])

In [53]:
daily_inventory['snapshot_date']=pd.to_datetime(daily_inventory['snapshot_date'])

In [54]:
suppliers['contract_start_date']=pd.to_datetime(suppliers['contract_start_date'])

In [55]:
#verify missing values

In [56]:
product.isnull().sum()

sku_id                 0
product_name           0
category               0
sub_category           0
brand                  0
product_type           0
size_label             0
launch_date            0
shelf_life_months      0
parent_sku             0
default_price          0
primary_supplier_id    0
is_active              0
country_of_origin      0
online_only            0
avg_rating             0
rating_count           0
is_discontinued        0
dtype: int64

In [57]:
sales.isnull().sum()

sale_id                0
order_id               0
date                   0
sku_id                 0
channel                0
quantity               0
unit_price             0
promo_flag             0
discount_pct           0
event_name             0
customer_segment_id    0
customer_segment       0
device_type            0
payment_method         0
shipping_fee           0
voucher_amount         0
net_revenue            0
returned_flag          0
quarter_bucket         0
month                  0
dtype: int64

In [58]:
#verify data types

In [59]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sku_id               80 non-null     str
 1   product_name         80 non-null     str
 2   category             80 non-null     str
 3   sub_category         80 non-null     str
 4   brand                80 non-null     str
 5   product_type         80 non-null     str
 6   size_label           80 non-null     str
 7   launch_date          80 non-null     datetime64[us]
 8   shelf_life_months    80 non-null     float64
 9   parent_sku           80 non-null     str
 10  default_price        80 non-null     float64
 11  primary_supplier_id  80 non-null     int64
 12  is_active            80 non-null     bool
 13  country_of_origin    80 non-null     str
 14  online_only          80 non-null     bool
 15  avg_rating           80 non-null     float64
 16  rating_count         80 non-null     int64
 17  is_discontinued      80 non-null     bool
dtypes: bool(3), datetime64[us](1), float64(3), int64(2), str(9)
memory usage: 9.7 KB

In [60]:
purchase_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1144 non-null   int64
 1   po_id                   1144 non-null   str
 2   sku_id                  1144 non-null   str
 3   supplier_id             1144 non-null   int64
 4   po_date                 1144 non-null   datetime64[us]
 5   promised_delivery_date  1144 non-null   datetime64[us]
 6   delivery_date           1144 non-null   datetime64[us]
 7   order_qty               1144 non-null   int64
 8   unit_cost               1144 non-null   float64
 9   shipping_mode           1144 non-null   str
 10  status                  1144 non-null   str
 11  incoterm                1144 non-null   str
 12  currency                1144 non-null   str
 13  freight_cost            1144 non-null   float64
 14  duty_cost               1144 non-null   float64
dtypes: datetime64[us](3), float64(3), int64(3), str(6)
memory usage: 134.2 KB

In [61]:
inventory_snapshot.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   snapshot_date         80 non-null     datetime64[us]
 1   sku_id                80 non-null     str
 2   current_stock         80 non-null     int64
 3   incoming_stock        80 non-null     int64
 4   stock_age_days        80 non-null     int64
 5   warehouse_stock       80 non-null     int64
 6   retail_stock          80 non-null     int64
 7   amazon_allocated      80 non-null     int64
 8   tiktokshop_allocated  80 non-null     int64
 9   zalora_allocated      80 non-null     int64
 10  reorder_point         80 non-null     int64
 11  safety_stock          80 non-null     int64
 12  backorder_qty         80 non-null     int64
 13  opening_buffer        80 non-null     int64
dtypes: datetime64[us](1), int64(12), str(1)
memory usage: 8.9 KB

In [62]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 160131 entries, 0 to 160130
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   sale_id              160131 non-null  int64
 1   order_id             160131 non-null  str
 2   date                 160131 non-null  datetime64[us]
 3   sku_id               160131 non-null  str
 4   channel              160131 non-null  str
 5   quantity             160131 non-null  int64
 6   unit_price           160131 non-null  float64
 7   promo_flag           160131 non-null  int64
 8   discount_pct         160131 non-null  float64
 9   event_name           160131 non-null  str
 10  customer_segment_id  160131 non-null  int64
 11  customer_segment     160131 non-null  str
 12  device_type          160131 non-null  str
 13  payment_method       160131 non-null  str
 14  shipping_fee         160131 non-null  float64
 15  voucher_amount       160131 non-null  float64
 16  net_revenue          160131 non-null  float64
 17  returned_flag        160131 non-null  int64
 18  quarter_bucket       160131 non-null  str
 19  month                160131 non-null  str
dtypes: datetime64[us](1), float64(5), int64(5), str(9)
memory usage: 24.4 MB

In [63]:
daily_inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 204560 entries, 0 to 204559
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   snapshot_date         204560 non-null  datetime64[us]
 1   sku_id                204560 non-null  str
 2   current_stock         204560 non-null  int64
 3   daily_sales           204560 non-null  int64
 4   incoming_stock        204560 non-null  int64
 5   warehouse_stock       204560 non-null  int64
 6   retail_stock          204560 non-null  int64
 7   amazon_allocated      204560 non-null  int64
 8   tiktokshop_allocated  204560 non-null  int64
 9   zalora_allocated      204560 non-null  int64
 10  reorder_point         204560 non-null  int64
 11  safety_stock          204560 non-null  int64
dtypes: datetime64[us](1), int64(10), str(1)
memory usage: 18.7 MB

In [64]:
suppliers.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   supplier_id            25 non-null     int64
 1   supplier_name          25 non-null     str
 2   region                 25 non-null     str
 3   default_shipping_mode  25 non-null     str
 4   status                 25 non-null     str
 5   lead_time_category     25 non-null     str
 6   min_order_qty          25 non-null     int64
 7   contract_start_date    25 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 1.7 KB

In [65]:
#save cleaned dataset

In [66]:
product.to_csv("product_cleaned.csv")

In [67]:
purchase_orders.to_csv("purchase_orders_cleaned.csv")

In [68]:
inventory_snapshot.to_csv("inventory_snapshot_cleaned.csv")

In [69]:
sales.to_csv("sales_cleaned.csv")

In [70]:
daily_inventory.to_csv("daily_inventory_cleaned.csv")

In [71]:
suppliers.to_csv("suppliers_cleaned.csv")

In [72]:
product_cleaned=pd.read_csv("product_cleaned.csv")
purchase_orders_cleaned=pd.read_csv("purchase_orders_cleaned.csv")
inventory_snapshot_cleaned=pd.read_csv("inventory_snapshot_cleaned.csv")
sales_cleaned=pd.read_csv("sales_cleaned.csv")
daily_inventory_cleaned=pd.read_csv("daily_inventory_cleaned.csv")
suppliers_cleaned=pd.read_csv("suppliers_cleaned.csv")

In [73]:
import pandas as pd
from sqlalchemy import create_engine
engine=create_engine=("mysql+pymysql://root:surekhasahu%40123@localhost:3306/ECOMMERCE_AND_RETAIL_SUPPLY_CHAIN")
print("starting data transfer to mysql...")

starting data transfer to mysql...

In [74]:
product.to_sql("product_cleaned",con=engine,if_exists="replace",index=False)

80

In [77]:
purchase_orders.to_sql("purchase_orders_cleaned",con=engine,if_exists="replace",index=False)

1144

In [78]:
inventory_snapshot.to_sql("inventory_snapshot_cleaned",con=engine,if_exists="replace",index=False)

80

In [81]:
sales.to_sql("sales_cleaned",con=engine,if_exists="replace",index=False)

160131

In [82]:
daily_inventory.to_sql("daily_inventory_cleaned",con=engine,if_exists="replace",index=False)

204560

In [83]:
suppliers.to_sql("suppliers_cleaned",con=engine,if_exists="replace",index=False)

25